import { describe, it, expect, vi, afterEach } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { analyzeImpact } from "../src/change/impact.js";
import { resolveReviewers } from "../src/review/resolver.js";
import { safeRelativePath } from "../src/security/filesystem.js";
import { buildPrComment } from "../src/github/comment.js";
import { analyzePr, runPrIntegration } from "../src/github/github.js";
import {
  parseRepo,
  resolvePullNumber,
  resolveGitHubToken,
  postIssueComment,
  requestReviewers,
  GitHubApiError,
} from "../src/github/client.js";
import { makeGitRepo, buildFixtureState, fixtureRoot } from "./helpers.js";
import type { ChangedHunk } from "../src/change/diff.js";

function hunk(relPath: string, addedLines: number[]): ChangedHunk {
  const safe = safeRelativePath(relPath);
  if (!safe.ok) throw safe.error;
  return { relPath: safe.value, addedLines, removedLineCount: 1, isNewFile: false, isDeletedFile: false };
}

function checkoutModify(dir: string): void {
  const file = path.join(dir, "src/checkout/CheckoutService.ts");
  const content = fs.readFileSync(file, "utf8");
  fs.writeFileSync(
    file,
    content + "\nexport function checkoutV2(cartId: string): string {\n  return checkout(cartId) + \"-v2\";\n}\n",
  );
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("buildPrComment", () => {
  it("includes severity, changed symbols, reviewers and authority approvers", () => {
    const root = fixtureRoot("cross-team");
    const state = buildFixtureState(root);
    const impact = analyzeImpact(root, state.config, state.graph, state.index, state.ownership, state.contexts, {
      changes: [hunk("src/checkout/CheckoutService.ts", [3])],
      developerTeam: "checkout-team",
    });
    expect(impact.ok).toBe(true);
    if (!impact.ok) return;
    const review = resolveReviewers(root, state.config, impact.value);
    const comment = buildPrComment(impact.value, review, { enforcePolicy: true });

    expect(comment).toContain("## NodeNet impact analysis");
    expect(comment).toContain("Severity: HIGH");
    expect(comment).toContain("checkout");
    expect(comment).toContain("payment-team");
    expect(comment).toContain("finance-team");
    expect(comment).toContain("PAYMENT-003");
    expect(comment).toContain("Ownership boundary crossed");
    expect(comment).toContain("_Generated by NodeNet");
  });

  it("flags hardened/mandatory authority for policy enforcement", () => {
    const root = fixtureRoot("cross-team");
    const state = buildFixtureState(root);
    const impact = analyzeImpact(root, state.config, state.graph, state.index, state.ownership, state.contexts, {
      changes: [hunk("src/payment/PaymentService.ts", [2])],
      developerTeam: "checkout-team",
    });
    expect(impact.ok).toBe(true);
    if (!impact.ok) return;
    const review = resolveReviewers(root, state.config, impact.value);
    const comment = buildPrComment(impact.value, review, { enforcePolicy: true });
    expect(comment).toContain("SEC-009");
    expect(comment).toContain("Policy");
  });
});

describe("GitHub client", () => {
  it("parseRepo splits owner and repo", () => {
    expect(parseRepo("acme/cart")).toEqual({ owner: "acme", repo: "cart" });
    expect(() => parseRepo("acme")).toThrow(/expected "owner\/repo"/);
  });

  it("resolvePullNumber reads flag, env and GITHUB_REF", () => {
    expect(resolvePullNumber("42", {})).toBe(42);
    expect(resolvePullNumber(undefined, { GITHUB_PR_NUMBER: "7" })).toBe(7);
    expect(resolvePullNumber(undefined, { GITHUB_REF: "refs/pull/123/merge" })).toBe(123);
    expect(() => resolvePullNumber(undefined, {})).toThrow(/Pull request number not provided/);
  });

  it("resolveGitHubToken prefers GITHUB_TOKEN", () => {
    expect(resolveGitHubToken({ GITHUB_TOKEN: "a", GH_TOKEN: "b" })).toBe("a");
    expect(resolveGitHubToken({ GH_TOKEN: "b" })).toBe("b");
    expect(resolveGitHubToken({})).toBeUndefined();
  });

  it("postIssueComment posts with auth header", async () => {
    const fetchMock = vi.fn(async () => new Response(JSON.stringify({ id: 1 }), { status: 201 }));
    vi.stubGlobal("fetch", fetchMock);
    await postIssueComment(
      { token: "secret", apiUrl: "https://api.github.com" },
      { owner: "acme", repo: "cart", issueNumber: 42, body: "hello" },
      fetchMock as unknown as typeof fetch,
    );
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0] as unknown as [string, RequestInit];
    expect(url).toBe("https://api.github.com/repos/acme/cart/issues/42/comments");
    expect(init.method).toBe("POST");
    expect((init.headers as Record<string, string>)["Authorization"]).toBe("Bearer secret");
    expect(JSON.parse(String(init.body))).toEqual({ body: "hello" });
  });

  it("requestReviewers splits users and teams", async () => {
    const fetchMock = vi.fn(async () => new Response("{}", { status: 201 }));
    vi.stubGlobal("fetch", fetchMock);
    await requestReviewers(
      { token: "t", apiUrl: "https://api.github.com" },
      { owner: "acme", repo: "cart", pullNumber: 42, reviewers: ["payment-team"], teamReviewers: ["acme/finance"] },
      fetchMock as unknown as typeof fetch,
    );
    const [url, init] = fetchMock.mock.calls[0] as unknown as [string, RequestInit];
    expect(url).toBe("https://api.github.com/repos/acme/cart/pulls/42/requested_reviewers");
    const body = JSON.parse(String(init.body)) as Record<string, string[]>;
    expect(body["reviewers"]).toEqual(["payment-team"]);
    expect(body["team_reviewers"]).toEqual(["acme/finance"]);
  });

  it("throws GitHubApiError on non-2xx", async () => {
    const fetchMock = vi.fn(async () => new Response(JSON.stringify({ message: "nope" }), { status: 403 }));
    vi.stubGlobal("fetch", fetchMock);
    await expect(
      postIssueComment(
        { token: "t", apiUrl: "https://api.github.com" },
        { owner: "acme", repo: "cart", issueNumber: 1, body: "x" },
        fetchMock as unknown as typeof fetch,
      ),
    ).rejects.toBeInstanceOf(GitHubApiError);
  });
});

describe("GitHub PR integration", () => {
  it("analyzePr produces the cross-team MVP impact on a real PR diff", () => {
    const root = makeGitRepo("cross-team", checkoutModify);
    const state = buildFixtureState(root);
    const analyzed = analyzePr(root, state.config, state.graph, state.index, state.ownership, state.contexts, {
      base: "main",
    });
    expect(analyzed.ok).toBe(true);
    if (!analyzed.ok) return;
    const { impact, review, comment } = analyzed.value;

    expect(impact.severity).toBe("HIGH");
    expect(impact.crossTeamBoundary).toBe(true);
    expect(impact.changedFiles.map((f) => f.toString())).toContain("src/checkout/CheckoutService.ts");

    const required = review.required.map((r) => r.target);
    const authority = review.authorityRequired.map((r) => r.target);
    expect(required).toContain("payment-team");
    expect(authority).toContain("finance-team");

    expect(comment).toContain("Severity: HIGH");
    expect(comment).toContain("finance-team");
  });

  it("runPrIntegration posts the comment and requests declared reviewers only", async () => {
    const root = makeGitRepo("cross-team", checkoutModify);
    const state = buildFixtureState(root);
    const fetchMock = vi.fn(async () => new Response("{}", { status: 201 }));
    vi.stubGlobal("fetch", fetchMock);

    const result = await runPrIntegration(root, state.config, state, {
      repo: "acme/cart",
      pr: 42,
      base: "main",
      comment: true,
      requestReviewers: true,
      token: "tok",
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.commentPosted).toBe(true);
    expect(result.value.requestedReviewers).toContain("payment-team");
    expect(fetchMock).toHaveBeenCalledTimes(2);

    const urls = fetchMock.mock.calls.map((c) => String((c as unknown as [string])[0]));
    expect(urls[0]).toContain("/issues/42/comments");
    expect(urls[1]).toContain("/pulls/42/requested_reviewers");
  });

  it("requires a token to post", async () => {
    const root = makeGitRepo("cross-team", checkoutModify);
    const state = buildFixtureState(root);
    const result = await runPrIntegration(root, state.config, state, {
      repo: "acme/cart",
      pr: 1,
      base: "main",
      comment: true,
      token: undefined,
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toContain("GITHUB_TOKEN");
  });
});
