/**
 * GitHub PR comment builder (NodeNet spec §57).
 *
 * Turns an ImpactReport + ReviewResolution into a deterministic Markdown
 * comment. The comment contains file paths, context ids, owners and review
 * reasons only — never source content or secrets. All claims are
 * explainable (spec §4: every relationship has provenance).
 */

import type { ImpactReport } from "../change/impact.js";
import type { ReviewResolution } from "../review/resolver.js";
import { authorityRank } from "../authority/authority.js";
import { isBlockingAuthority } from "../authority/authority.js";

export interface PrCommentOptions {
  /** Team of the change author, if known. */
  authorTeam?: string;
  /** When true, CRITICAL findings are emphasized for merge-block policy. */
  enforcePolicy?: boolean;
}

/** Build the full PR comment body. */
export function buildPrComment(impact: ImpactReport, review: ReviewResolution, opts: PrCommentOptions = {}): string {
  const lines: string[] = [];
  lines.push("## NodeNet impact analysis");
  lines.push("");
  lines.push(`**Severity: ${impact.severity}**`);
  if (impact.severityReasons.length > 0) {
    for (const reason of impact.severityReasons) lines.push(`- ${reason}`);
  }
  lines.push("");

  lines.push("### Changes");
  lines.push("");
  for (const s of impact.changedSymbols) {
    lines.push(`- \`${s.changeKind.toUpperCase()}\` \`${s.symbolName}\` — \`${s.relPath.toString()}:${s.startLine}\``);
  }
  if (impact.changedSymbols.length === 0) lines.push("- (no symbol-level changes detected)");
  lines.push("");

  if (impact.crossTeamBoundary) {
    lines.push("### Ownership boundary crossed");
    lines.push("");
    for (const b of impact.boundaries) {
      lines.push(`- \`${b.fromTeam}\` → \`${b.toTeam}\` (via \`${b.viaFile}\`)`);
    }
    lines.push("");
  }

  if (impact.affectedContexts.length > 0) {
    lines.push("### Affected living context");
    lines.push("");
    for (const ctx of impact.affectedContexts) {
      const approvers = ctx.approvedBy.length > 0 ? ` (approvers: ${ctx.approvedBy.join(", ")})` : "";
      lines.push(`- \`${ctx.id}\` [${ctx.status}] ${ctx.authority} — ${ctx.title}${approvers}`);
    }
    lines.push("");
  }

  lines.push("### Reviewers");
  lines.push("");
  appendGroup(lines, "Required", review.required);
  appendGroup(lines, "Authority approval required", review.authorityRequired);
  appendGroup(lines, "Suggested", review.suggested);
  if (review.required.length + review.authorityRequired.length + review.suggested.length === 0) {
    lines.push("- No reviewers required.");
  }
  lines.push("");

  if (opts.enforcePolicy && isBlocking(impact, review)) {
    lines.push("> **Policy:** this change affects hardened/mandatory context and is **flagged** for approval before merge.");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by NodeNet — deterministic analysis of the repository graph, ownership and living context._");
  return lines.join("\n");
}

function appendGroup(lines: string[], title: string, items: ReviewResolution["required"]): void {
  if (items.length === 0) return;
  lines.push(`**${title}:**`);
  lines.push("");
  for (const item of items) {
    lines.push(`- \`${item.target}\``);
    for (const reason of item.reasons) lines.push(`  - ${reason}`);
  }
  lines.push("");
}

function isBlocking(impact: ImpactReport, review: ReviewResolution): boolean {
  if (review.authorityRequired.length === 0) return false;
  return impact.affectedContexts.some(
    (ctx) => isBlockingAuthority(ctx.authority) || authorityRank(ctx.authority) >= 4,
  );
}
