/**
 * Static graph visualization (NodeNet spec §53).
 *
 * Generates a single self-contained HTML file (no server required).
 * Layers are color-coded: Code (blue), Context (purple), Ownership (green),
 * Authority (amber). The page is static and never executes repository code.
 */

import type { Graph } from "../graph/graph.js";
import { nodeLabel } from "../graph/nodes.js";
import type { GraphNode } from "../graph/nodes.js";

const CODE_KINDS = new Set([
  "repository", "workspace", "package", "directory", "file", "function", "method",
  "class", "interface", "typeAlias", "enum", "variable", "reactComponent",
  "reactHook", "apiRoute", "middleware", "test", "configuration",
]);

export function renderGraphHtml(graph: Graph, title = "NodeNet Graph"): string {
  const nodes: GraphNode[] = [...graph.nodes()];
  const codeNodes = nodes.filter((n) => CODE_KINDS.has(n.kind));
  const contextNodes = nodes.filter((n) => n.kind.endsWith("Rule") || n.kind === "architectureDecision" || n.kind === "securityPolicy" || n.kind === "codingConvention" || n.kind === "requirement" || n.kind === "specification" || n.kind === "complianceRule" || n.kind === "operationalRule" || n.kind === "incidentLearning" || n.kind === "assumption" || n.kind === "domainRule" || n.kind === "externalConstraint");
  const actorNodes = nodes.filter((n) => n.kind === "team" || n.kind === "developer" || n.kind === "role");

  const edgeRows: string[] = [];
  for (const edge of graph.edges()) {
    const from = graph.getNode(edge.from);
    const to = graph.getNode(edge.to);
    if (!from || !to) continue;
    const relClass = edge.relation === "governed_by" || edge.relation === "applies_to" || edge.relation === "conflicts_with"
      ? "ctx"
      : edge.relation === "owned_by" || edge.relation === "approved_by" || edge.relation === "reviews"
        ? "own"
        : "code";
    edgeRows.push(
      `<tr><td class="mono">${escapeHtml(nodeLabel(from))}</td><td class="rel ${relClass}">${edge.relation.replace(/_/g, " ")}</td><td class="mono">${escapeHtml(nodeLabel(to))}</td></tr>`,
    );
  }

  const renderList = (items: GraphNode[], color: string): string =>
    items
      .map(
        (n) =>
          `<li><span class="dot ${color}"></span><code>${escapeHtml(nodeLabel(n))}</code></li>`,
      )
      .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 1100px; padding: 0 1rem; }
  h1 { font-size: 1.4rem; }
  h2 { font-size: 1rem; margin-top: 2rem; border-bottom: 1px solid #8883; padding-bottom: .3rem; }
  .layer { display: flex; flex-wrap: wrap; gap: .6rem 1.4rem; padding: 0; }
  .layer li { list-style: none; font-size: .85rem; }
  code { background: #8882; padding: 1px 5px; border-radius: 4px; }
  .dot { display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 6px; }
  .dot.code { background: #3b82f6; }
  .dot.ctx { background: #a855f7; }
  .dot.own { background: #22c55e; }
  table { width: 100%; border-collapse: collapse; font-size: .82rem; }
  td, th { text-align: left; padding: 4px 8px; border-bottom: 1px solid #8882; }
  .mono { font-family: ui-monospace, monospace; }
  .rel { font-weight: 600; text-transform: uppercase; font-size: .72rem; letter-spacing: .04em; }
  .rel.code { color: #3b82f6; }
  .rel.ctx { color: #a855f7; }
  .rel.own { color: #16a34a; }
  .summary { color: #888; font-size: .85rem; }
  details { margin-top: 1rem; }
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
<p class="summary">${nodes.length} nodes, ${graph.edgeCount} edges · generated by NodeNet · static export</p>

<h2>Code layer</h2>
<ul class="layer">${renderList(codeNodes, "code")}</ul>

<h2>Living Context layer</h2>
<ul class="layer">${renderList(contextNodes, "ctx")}</ul>

<h2>Ownership layer</h2>
<ul class="layer">${renderList(actorNodes, "own")}</ul>

<h2>Relationships</h2>
<details open>
<summary>${edgeRows.length} edges</summary>
<table>
<thead><tr><th>From</th><th>Relationship</th><th>To</th></tr></thead>
<tbody>${edgeRows.join("\n")}</tbody>
</table>
</details>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
